version: 1.0.{build}
image: Visual Studio 2015

platform:
- x86
- x64

init:
- ps: >-
    echo $env:PLATFORM

    if ($env:PLATFORM -eq "x86") {
      $Env:JAVA_HOME = "C:\Program Files (x86)\Java\jdk1.8.0"
      echo "32 Bit"
    }

    else {
      $Env:JAVA_HOME = "C:\Program Files\Java\jdk1.8.0"
      echo "64 bit"
    }

clone_script:
- cmd: >-
    git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
    
    cd %APPVEYOR_BUILD_FOLDER%
    
    git checkout -qf %APPVEYOR_REPO_COMMIT%
    
    git submodule update --init --recursive

build_script:
- cmd: gradlew.bat build


artifacts:

- path: build/libs/CoordinateGui.jar
  name: CoordinateGui

- path: build/distributions
  name: CoordinateGuiStandalone

 