name: Java CI

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
        - os: windows-latest
          artifact-name: Win64

        - os: ubuntu-latest
          artifact-name: Linux
          build-options: "-x test"

        - os: macos-latest
          artifact-name: macOS
          build-options: "-x test"

    runs-on: ${{ matrix.platform.os }}

    steps:
    - uses: actions/checkout@v1

    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Build
      run: ./gradlew build publish ${{ matrix.platform.build-options }}

    - name: Publish Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.platform.artifact-name }}
        path: build/maven_repo
