name: Java CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Gradle
      run: ./gradlew build
    - name: Get Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: my-artifact_${{ matrix.platform }}
        path: build/maven_repo
